version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # raíz del proyecto
    schedule:
      interval: "weekly" # o "daily", "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
